/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void menu() {
        System.out.println("Menu:");
        System.out.println("0. Exit");
        System.out.println("1. Add an element to the list");
        System.out.println("2. Remove an element from the list");
        System.out.println("3. Print the contents of the list");
        System.out.println("4. Check if the value is in the list");
        System.out.println("5. Alter an element of the list");
        
    }
    public static void main(String[] args) {
        // Task 1
        // System.out.println("Enter a set of numbers (x y z...)");
        // Scanner scanner = new Scanner(System.in);

        // String inp = scanner.nextLine();

        // List<Integer> list = new ArrayList<>();

        // for( var str : inp.split(" ")) {
        //     try {
        //         list.add(Integer.parseInt(str));
        //     } catch (Exception e){}
        // }

        

        // while (true) {
        //     menu();
        //     inp = "" + scanner.nextInt();

        //     switch (Integer.parseInt(inp)) {
        //         case 0:
        //             return;
        //         case 1:
        //             System.out.println("Enter a value to add: ");
        //             list.add(scanner.nextInt());
        //             System.out.println("Done.");
        //             break;
        //         case 2: 
        //             System.out.println("Enter the index of the element to remove: ");
        //             list.remove(scanner.nextInt());
        //             System.out.println("Done.");
        //             break;
        //         case 3:
        //             System.out.println(list.toString());
        //             break;
        //         case 4:
        //             System.out.println("Enter a value to check: ");
        //             System.out.println(list.contains(scanner.nextInt()));
        //             break;
        //         case 5:
        //             System.out.println("Enter the index of the element to remove and its new value: ");
        //             list.set(scanner.nextInt(), scanner.nextInt());
        //             System.out.println("Done.");
        //             break;
        //         default:
        //             break;
        //     }
        // }

        // Task 2
        
    }
}
